# Generated by Django 3.2.2 on 2021-10-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currently_working',
            field=models.CharField(max_length=20, verbose_name='currently_working'),
        ),
        migrations.AlterField(
            model_name='user',
            name='how_did_you_hear_about_us',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='how_did_you_hear_about_us'),
        ),
        migrations.AlterField(
            model_name='user',
            name='own_laptop',
            field=models.CharField(max_length=20, verbose_name='own_laptop'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uploaded_id_url',
            field=models.CharField(max_length=300, null=True, verbose_name='ID url'),
        ),
    ]
