# Generated by Django 3.2.2 on 2021-10-25 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('paystack_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('batch', models.CharField(default=main.models.batch_date, max_length=200)),
                ('time_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=15)),
                ('account_name', models.CharField(max_length=250)),
                ('recipient_code', models.CharField(blank=True, max_length=200, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.bank')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2021, 10, 25, 12, 23, 33, 972805, tzinfo=utc))),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='main.student')),
            ],
        ),
    ]
