# Generated by Django 3.2.2 on 2021-08-26 10:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique_for_month=True, unique_for_year=True)),
                ('batch', models.CharField(default=main.models.batch_date, max_length=200)),
                ('time_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2021, 8, 26, 10, 33, 12, 870941, tzinfo=utc))),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='main.student')),
            ],
        ),
    ]
