# Generated by Django 3.2.2 on 2021-10-25 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbankdetail',
            name='month',
            field=models.CharField(default=main.models.batch_date, max_length=300),
        ),
        migrations.AlterField(
            model_name='studentbankdetail',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
