# Generated by Django 3.2.2 on 2021-08-26 10:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 10, 44, 48, 9560, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(default='<function batch_date at 0x000002014AFD7160>', max_length=200),
        ),
    ]
