# Generated by Django 3.2.2 on 2021-08-26 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210826_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 10, 47, 33, 422457, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(default=main.models.batch_date, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
