# Generated by Django 3.2.2 on 2021-08-26 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210826_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentbankdetail',
            old_name='account_num',
            new_name='account_number',
        ),
        migrations.RemoveField(
            model_name='studentbankdetail',
            name='recepient_num',
        ),
        migrations.AddField(
            model_name='studentbankdetail',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 15, 43, 46, 436924, tzinfo=utc)),
        ),
    ]
