# Generated by Django 3.2.2 on 2021-08-31 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210826_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbankdetail',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 9, 47, 3, 329346, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
